<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Penelitian_fas fa-users fa-5x ic</name>
   <tag></tag>
   <elementGuidId>7014a6f4-7148-47cc-bbb6-3c7857aca280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/article/div[2]/div[3]/div/div/div/div/div[3]/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-users fa-5x ic</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/article[@class=&quot;single-post&quot;]/div[@class=&quot;post-content&quot;]/div[@class=&quot;row tpb-row tpb-custom-row-21934284085 tengah&quot;]/div[@class=&quot;tpb tpb-html col-md-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 widget-html&quot;]/div[@class=&quot;row tpb-row&quot;]/div[@class=&quot;tpb tpb-icon_fa col-md-4&quot;]/div[@class=&quot;col-md-12 tpb-icon-container&quot;]/a[@class=&quot;my_icon&quot;]/i[@class=&quot;fas fa-users fa-5x ic&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/article/div[2]/div[3]/div/div/div/div/div[3]/div/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/i</value>
   </webElementXpaths>
</WebElementEntity>
